<?php

/**
 * @file
 * Contains ecole.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ecole_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ecole module.
    case 'help.page.ecole':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ecole') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ecole_theme() {


		return array(
			// Blocks themes
			// ---------------------------------------------------------------------
			
			'job_add_form' => array(
				'render element' => 'form',
				'template' => 'job-add-form',
			),
			'jobsearch_form' => array(
				'render element' => 'form',
				'template' => 'jobsearch-form',
			)		
		);
	
}